### ISSUE TITLE
Question: Mixtrack II Compatibility

### ISSUE THREAD

**Issue by boustanihani** [tompreston/Mixxx-Numark-Mixtrack-Pro-II-Mappings#5]
Thanks for sharing.

Are the mappings also compatible with **Mixtrack II** ? => http://www.numark.com/product/mixtrack-ii

**Comment by tompreston** [comment]
You're welcome, but 've got no idea if it'll work with that mixer sorry. To be honest, these mappings aren't even perfect for the Pro II (though, they're better than anything else I found) -- I didn't finish it because I moved to Traktor after getting a mac (boo, I know :p).

If you know Javascript it's not too difficult to edit yourself.
